### ISSUE TITLE
Wrong version used in intro 

### ISSUE THREAD

**Issue by cderv** [EmilHvitfeldt/feature-engineering-az#15]
Just reading the intro I noticed 
![image](https://github.com/EmilHvitfeldt/feature-engineering-az/assets/6791940/d7bfb673-e121-41b7-906a-272e3069db16)

Looking at the source 
https://github.com/EmilHvitfeldt/feature-engineering-az/blob/a53aa6a435e48df8eef5a61e5c3483df79af4c88/index.qmd#L55-L55

I believe 

* R version is using `python_version` instead of `r_version`
* After Python version, this is not an inline code so `r_version` is show in HTML. 

Hope it helps. 

And Good project! 👍

**Comment by EmilHvitfeldt** [comment]
That was quite a typo, thanks for catching it!
