### ISSUE TITLE
Possible font problem

### ISSUE THREAD

**Issue by matthewsTam** [EmilHvitfeldt/feature-engineering-az#16]
in Section (as follows):
**7.1.2 Cons**
'Not all software solutions will not be helpful when applying this transformation to a constant variable. A division by 0 error is likely what you will see '---

There are two negations in the same phrase -- possibly, the second negation should be removed.
In the online version the  zero (0) appears similar in font to letter 'o'.
I can see this is not an actual typo, it is just the type of font that creates this confusion. Changing fonts may be a way to improve this.

Thank you so much for this comprehensive and well organized material. Very useful !
Tamara Matthews

**Comment by EmilHvitfeldt** [comment]
Thank you for your feedback, I tried rephrasing the sentence to avoid confusion. I hope you are enjoying the book so far!
