### ISSUE TITLE
TOC links broken

### ISSUE THREAD

**Issue by olivroy** [EmilHvitfeldt/feature-engineering-az#17]
at the bottom of 
https://feaz-book.com/numeric-maxabs#python-examples
![image](https://github.com/EmilHvitfeldt/feature-engineering-az/assets/52606734/18ef8494-d654-43e8-a555-9eaed27a2c88)

I wonder if the latest quarto 1.4.550 (or pre-release 1.5 addresses this) I have seen it in the Quarto repo, but I wonder if this can be fixed.

**Comment by EmilHvitfeldt** [comment]
Hello @olivroy thanks for the report! that is indeed not right. I'll see what I can do to fix it

**Comment by olivroy** [comment]
No longer an issue! I wonder if it solved itself via one of the Quarto 1.4 patches or you had to do something?
